import "./globals.css";

import Header from "@/components/header";
import type { Metadata } from "next";
import localFont from "next/font/local";

const tektur = localFont({
  src: [
    {
      path: "../public/fonts/Tektur-Narrow/TekturNarrow-Black.ttf",
      weight: "900",
    },
    {
      path: "../public/fonts/Tektur-Narrow/TekturNarrow-Bold.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/Tektur-Narrow/TekturNarrow-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/Tektur-Narrow/TekturNarrow-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/Tektur-Narrow/TekturNarrow-SemiBold.ttf",
      weight: "600",
    },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tektur.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
